FROM node:22-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_AUTH_OTP_EXPIRY_SECONDS=3600
ARG VITE_AUTH_OTP_RESEND_SECONDS=60

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_AUTH_OTP_EXPIRY_SECONDS=$VITE_AUTH_OTP_EXPIRY_SECONDS
ENV VITE_AUTH_OTP_RESEND_SECONDS=$VITE_AUTH_OTP_RESEND_SECONDS

RUN npm run build:node

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

COPY --from=build /app/.output ./.output

EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]
