export type MachineSpecificationRow = {
  label: string;
  values: string[];
};

export type MachineSpecificationTable = {
  title: string;
  columns: string[];
  rows: MachineSpecificationRow[];
  sourceUrl: string;
  note?: string;
};

const referenceNote =
  "Technical figures are based on the supplied Modtech master specification sheets and are for reference. Final values may change with the approved machine configuration; contact Modtech Sales for the project datasheet.";

const table = (
  title: string,
  columns: string[],
  rows: Array<[string, ...string[]]>,
  sourceUrl: string,
  note?: string,
): MachineSpecificationTable => ({
  title,
  columns,
  rows: rows.map(([label, ...values]) => ({ label, values })),
  sourceUrl,
  note,
});

const fourPillarWaxModels = [
  "SOL-Mod-12T-4P",
  "SOL-Mod-30T-4P",
  "SOL-Mod-50T-4P",
  "SOL-Mod-100T-4P",
];
const cFrameWaxModels = ["SOL-Mod-12T-CF", "SOL-Mod-30T-CF", "SOL-Mod-50T-CF", "SOL-Mod-100T-CF"];
const automodeWaxModels = ["AM-Mod-12T", "AM-Mod-30T"];
const fourPillarCeramicModels = ["CI-Mod-30T-4P", "CI-Mod-50T-4P", "CI-Mod-100T-4P"];
const cFrameCeramicModels = ["CI-Mod-30T-CF", "CI-Mod-50T-CF", "CI-Mod-100T-CF"];

export const officialMachineSpecifications: Record<string, MachineSpecificationTable[]> = {
  "4-pillar-wax-injector": [
    table(
      "Machine and injection specification",
      fourPillarWaxModels,
      [
        ["Clamp force range", "2–12 MT", "5–30 MT", "10–50 MT", "20–100 MT"],
        ["Daylight maximum (mm)", "400", "600", "800", "1,000"],
        ["Daylight minimum (mm)", "70", "150", "150", "150"],
        ["Clearance between pillars (mm)", "450 × 450", "600 × 600", "800 × 800", "1,000 × 1,000"],
        ["Clamp-cylinder maximum stroke (mm)", "330", "450", "650", "850"],
        ["Platen speed down / up (mm/sec)", "60 / 75", "60 / 70", "60 / 70", "40 / 40"],
        ["Die clamping", "T-slot", "T-slot", "T-slot", "T-slot"],
        ["Single-shot capacity (cc)", "1,000", "2,000", "3,500", "3,500"],
        ["Soluble wax tank capacity", "30 L", "60 L", "100 L", "100 L"],
        ["Injection nozzle type", "Side, T-type", "Side", "Side", "Side"],
        [
          "Nozzle tip",
          "9.5 mm spherical radius",
          "9.5 mm spherical radius",
          "9.5 mm spherical radius",
          "9.5 mm spherical radius",
        ],
        ["Nozzle in-out travel (mm)", "200", "250", "300", "400"],
        ["Nozzle down position (mm)", "35", "70", "70", "70"],
        ["Nozzle up position (mm)", "265", "400", "500", "600"],
        ["Injection pressure (bar)", "5–50", "5–70", "5–70", "5–70"],
        ["Injection rate (cc/sec)", "Up to 200", "Up to 250", "Up to 250", "Up to 250"],
        [
          "Minimum die size W × D × H (mm)",
          "150 × 150 × 100",
          "150 × 150 × 160",
          "250 × 250 × 160",
          "350 × 350 × 200",
        ],
        [
          "Maximum die size W × D × H (mm)",
          "400 × 400 × 350",
          "550 × 550 × 550",
          "750 × 750 × 750",
          "950 × 950 × 950",
        ],
      ],
      "https://www.modtechworld.com/product-detail.php?id=13",
      referenceNote,
    ),
    table(
      "Controls, utilities and dimensions",
      fourPillarWaxModels,
      [
        [
          "Control system",
          '7" HMI, panel mounted',
          '15.6" HMI, pendant mounted',
          '15.6" HMI, pendant mounted',
          '15.6" HMI, pendant mounted',
        ],
        ["Die recipes", "Up to 200", "Up to 200", "Up to 200", "Up to 200"],
        ["Dwell time", "0–999 sec", "0–999 sec", "0–999 sec", "0–999 sec"],
        ["Working height (mm)", "1,000", "1,000", "1,000", "1,000"],
        ["Working width (mm)", "880", "920", "920", "1,460"],
        ["Working depth (mm)", "1,335", "750", "750", "980"],
        ["Electrical load", "12 kVA", "25 kVA", "35 kVA", "40 kVA"],
        [
          "Electrical supply",
          "420 V / 50 Hz / 3 phase",
          "420 V / 50 Hz / 3 phase",
          "420 V / 50 Hz / 3 phase",
          "420 V / 50 Hz / 3 phase",
        ],
        ["Air requirement", "Not stated", "6 CFM @ 6 bar", "6 CFM @ 6 bar", "6 CFM @ 6 bar"],
        ["Water requirement (LPM)", "30", "60", "60", "60"],
        ["Platen water-cooling passage", "Included", "Included", "Included", "Included"],
        ["Platen temperature control", "Included", "Included", "Included", "Included"],
        [
          "Wax-tank level indication",
          "Included, analogue sensor",
          "Included",
          "Included",
          "Included",
        ],
        ["Pattern ejector", "Included", "Included", "Included", "Included"],
        ["Essential one-year spare kit", "Included", "Included", "Included", "Included"],
        ["CE compliance", "Self-certified", "Self-certified", "Self-certified", "Self-certified"],
        ["Machine colour", "RAL 7035", "RAL 7035", "RAL 7035", "RAL 7035"],
        [
          "Approx. overall size W × D × H (mm)",
          "2,050 × 1,800 × 2,050 / 2,280",
          "3,500 × 2,150 × 2,900",
          "4,100 × 2,250 × 3,200",
          "4,550 × 2,300 × 3,900",
        ],
        ["Machine weight (kg)", "2,000", "5,500", "8,500", "17,000"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=13",
      referenceNote,
    ),
    table(
      "Optional / additional features",
      fourPillarWaxModels,
      [
        ["Platen heating system", "Not listed", "Available", "Available", "Available"],
        [
          "Single-station shuttle table",
          "Not listed",
          "Not listed",
          "Available – 500 kg",
          "Available – 1,000 kg",
        ],
        [
          "Dual-station shuttle table",
          "Not listed",
          "Not listed",
          "Available – 500 kg",
          "Available – 1,000 kg",
        ],
        ["Jib crane", "Not listed", "Not listed", "Available – 500 kg", "Available – 1,000 kg"],
        ["Electrical self-diagnostic", "Available", "Available", "Available", "Available"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=13",
    ),
  ],
  "c-frame-wax-injector": [
    table(
      "Machine and injection specification",
      cFrameWaxModels,
      [
        ["Clamp force range", "2–12 MT", "5–30 MT", "10–50 MT", "20–100 MT"],
        ["Daylight maximum (mm)", "400", "600", "800", "1,000"],
        ["Daylight minimum (mm)", "70", "150", "150", "150"],
        ["Clamp platen size W × D (mm)", "550 × 680", "720 × 550", "800 × 800", "1,000 × 1,000"],
        ["Clamp-cylinder maximum stroke (mm)", "330", "450", "650", "850"],
        ["Platen speed down / up (mm/sec)", "60 / 75", "60 / 70", "60 / 70", "40 / 40"],
        ["Die clamping", "T-slot", "T-slot", "T-slot", "T-slot"],
        ["Single-shot capacity (cc)", "1,000", "2,000", "3,500", "3,500"],
        ["Soluble wax tank capacity", "30 L", "60 L", "100 L", "100 L"],
        ["Injection nozzle type", "Side, T-type", "Side", "Side", "Side"],
        [
          "Nozzle tip",
          "9.5 mm spherical radius",
          "9.5 mm spherical radius",
          "9.5 mm spherical radius",
          "9.5 mm spherical radius",
        ],
        ["Nozzle in-out travel (mm)", "200", "250", "300", "400"],
        ["Nozzle down position (mm)", "35", "70", "70", "70"],
        ["Nozzle up position (mm)", "265", "400", "500", "600"],
        ["Injection pressure (bar)", "5–50", "5–70", "5–70", "5–70"],
        ["Injection rate (cc/sec)", "Up to 200", "Up to 250", "Up to 250", "Up to 250"],
        [
          "Minimum die size W × D × H (mm)",
          "150 × 150 × 100",
          "150 × 150 × 160",
          "250 × 250 × 160",
          "350 × 350 × 200",
        ],
        [
          "Maximum die size W × D × H (mm)",
          "400 × 400 × 350",
          "550 × 550 × 550",
          "750 × 750 × 750",
          "950 × 950 × 950",
        ],
      ],
      "https://www.modtechworld.com/product-detail.php?id=14",
      referenceNote,
    ),
    table(
      "Controls, utilities and dimensions",
      cFrameWaxModels,
      [
        [
          "Control system",
          '7" HMI, panel mounted',
          '15.6" HMI, pendant mounted',
          '15.6" HMI, pendant mounted',
          '15.6" HMI, pendant mounted',
        ],
        ["Die recipes", "Up to 200", "Up to 200", "Up to 200", "Up to 200"],
        ["Dwell time", "0–999 sec", "0–999 sec", "0–999 sec", "0–999 sec"],
        ["Working height (mm)", "1,000", "1,000", "1,000", "1,000"],
        ["Working width (mm)", "880", "920", "920", "1,460"],
        ["Working depth (mm)", "1,335", "750", "750", "980"],
        ["Electrical load", "12 kVA", "25 kVA", "35 kVA", "40 kVA"],
        [
          "Electrical supply",
          "420 V / 50 Hz / 3 phase",
          "420 V / 50 Hz / 3 phase",
          "420 V / 50 Hz / 3 phase",
          "420 V / 50 Hz / 3 phase",
        ],
        ["Air requirement", "Not stated", "6 CFM @ 6 bar", "6 CFM @ 6 bar", "6 CFM @ 6 bar"],
        ["Water requirement (LPM)", "30", "60", "60", "60"],
        ["Platen water-cooling passage", "Included", "Included", "Included", "Included"],
        ["Platen temperature control", "Included", "Included", "Included", "Included"],
        [
          "Wax-tank level indication",
          "Included, analogue sensor",
          "Included",
          "Included",
          "Included",
        ],
        ["Pattern ejector", "Optional", "Included", "Included", "Included"],
        ["Essential one-year spare kit", "Included", "Included", "Included", "Included"],
        ["CE compliance", "Self-certified", "Self-certified", "Self-certified", "Self-certified"],
        ["Machine colour", "RAL 7035", "RAL 7035", "RAL 7035", "RAL 7035"],
        [
          "Approx. overall size W × D × H (mm)",
          "1,800 × 1,550 × 2,150 / 2,325",
          "3,500 × 2,150 × 2,900",
          "4,100 × 2,250 × 3,200",
          "4,550 × 2,300 × 3,900",
        ],
        ["Machine weight (kg)", "2,500", "6,500", "9,000", "17,000"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=14",
      referenceNote,
    ),
    table(
      "Optional / additional features",
      cFrameWaxModels,
      [
        ["Platen heating system", "Not listed", "Available", "Available", "Available"],
        [
          "Single-station shuttle table",
          "Not listed",
          "Not listed",
          "Available – 500 kg",
          "Available – 1,000 kg",
        ],
        [
          "Dual-station shuttle table",
          "Not listed",
          "Not listed",
          "Available – 500 kg",
          "Available – 1,000 kg",
        ],
        ["Jib crane", "Not listed", "Not listed", "Available – 500 kg", "Available – 1,000 kg"],
        ["Electrical self-diagnostic", "Available", "Available", "Available", "Available"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=14",
    ),
  ],
  "automode-wax-injector": [
    table(
      "Detailed specification",
      automodeWaxModels,
      [
        ["Clamp force (MT)", "12T", "30T"],
        ["Daylight maximum (mm)", "800", "900"],
        ["Daylight minimum (mm)", "100", "100"],
        ["Clearance between pillars (mm)", "500 × 500", "600 × 600"],
        ["Die clamping", "T-slot", "T-slot"],
        ["Single-shot capacity (cc)", "2,500", "2,500"],
        ["Wax tank capacity", "120 L", "120 L"],
        ["Injection nozzle type", "Side", "Side"],
        ["Injection pressure (bar)", "3.5–70", "3.5–70"],
        ["Injection rate (cc/sec)", "250", "250"],
        ["Pattern ejector", "Included", "Included"],
        ["Melter unit", "Included", "Included"],
        ["Vacuum wax transfer unit", "Included", "Included"],
        ["Spray nozzle assembly", "Included", "Included"],
        ["Pattern catchment tank", "Included", "Included"],
        ["Control system", '15" touch screen', '15" touch screen'],
        ["Electrical standard", "380–420 V / 50 Hz / 3 phase", "380–420 V / 50 Hz / 3 phase"],
        ["Air requirement", "6 bar / 6 CFM", "6 bar / 6 CFM"],
        ["Water requirement (LPM)", "60", "60"],
        ["Overall size W × D × H (mm)", "4,400 × 1,800 × 2,800", "4,600 × 2,100 × 3,000"],
        ["Machine weight (kg)", "4,500", "5,500"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=15",
      referenceNote,
    ),
    table(
      "Optional / additional features",
      automodeWaxModels,
      [
        ["Through-pin injection", "Available", "Available"],
        ["Pneumatic core pull", "Available", "Available"],
        ["Jib crane", "Available – 100 kg", "Available – 100 kg"],
        ["Electrical self-diagnostic", "Available", "Available"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=15",
    ),
  ],
  "4-pillar-ceramic-injector": [
    table(
      "Detailed specification",
      fourPillarCeramicModels,
      [
        ["Clamp force (MT)", "30T", "50T", "100T"],
        ["Daylight maximum (mm)", "600", "800", "1,000"],
        ["Daylight minimum (mm)", "150", "150", "150"],
        ["Clearance between pillars (mm)", "600 × 600", "800 × 800", "1,000 × 1,000"],
        ["Die clamping", "T-slot", "T-slot", "T-slot"],
        ["Single-shot capacity (cc)", "1,500", "3,500", "3,500"],
        ["Ceramic tank capacity", "30 L", "80 L", "80 L"],
        ["Injection nozzle type", "Side", "Side", "Side"],
        ["Injection pressure (bar)", "3.5–70", "3.5–70", "3.5–70"],
        ["Injection rate (cc/sec)", "200", "250", "250"],
        ["Pattern ejector", "Included", "Included", "Included"],
        ["Control system", '15" touch screen', '15" touch screen', '15" touch screen'],
        [
          "Electrical standard",
          "380–420 V / 50 Hz / 3 phase",
          "380–420 V / 50 Hz / 3 phase",
          "380–420 V / 50 Hz / 3 phase",
        ],
        ["Air requirement", "6 bar / 6 CFM", "6 bar / 6 CFM", "6 bar / 6 CFM"],
        ["Water requirement (LPM)", "60", "60", "60"],
        [
          "Overall size W × D × H (mm)",
          "3,500 × 2,150 × 2,900",
          "4,100 × 2,250 × 3,200",
          "4,550 × 2,300 × 3,900",
        ],
        ["Machine weight (kg)", "5,500", "8,500", "17,000"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=17",
      referenceNote,
    ),
    table(
      "Optional / additional features",
      fourPillarCeramicModels,
      [
        ["Shuttle table (single / dual station)", "N/A", "Available", "Available"],
        ["Second ceramic tank", "Available", "Available", "Available"],
        ["Jib crane", "Available – 200 kg", "Available – 500 kg", "Available – 1,000 kg"],
        ["Platen heating system", "Available", "Available", "Available"],
        ["Electrical self-diagnostic", "Available", "Available", "Available"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=17",
    ),
  ],
  "c-frame-ceramic-injector": [
    table(
      "Detailed specification",
      cFrameCeramicModels,
      [
        ["Clamp force (MT)", "30T", "50T", "100T"],
        ["Daylight maximum (mm)", "600", "800", "1,000"],
        ["Daylight minimum (mm)", "150", "150", "150"],
        ["Clearance between pillars (mm)", "720 × 550", "800 × 800", "1,000 × 1,000"],
        ["Die clamping", "T-slot", "T-slot", "T-slot"],
        ["Single-shot capacity (cc)", "1,500", "3,500", "3,500"],
        ["Ceramic tank capacity", "30 L", "80 L", "80 L"],
        ["Injection nozzle type", "Side", "Side", "Side"],
        ["Injection pressure (bar)", "3.5–70", "3.5–70", "3.5–70"],
        ["Injection rate (cc/sec)", "200", "250", "250"],
        ["Pattern ejector", "Included", "Included", "Included"],
        ["Control system", '15" touch screen', '15" touch screen', '15" touch screen'],
        [
          "Electrical standard",
          "380–420 V / 50 Hz / 3 phase",
          "380–420 V / 50 Hz / 3 phase",
          "380–420 V / 50 Hz / 3 phase",
        ],
        ["Air requirement", "6 bar / 6 CFM", "6 bar / 6 CFM", "6 bar / 6 CFM"],
        ["Water requirement (LPM)", "60", "60", "60"],
        [
          "Overall size W × D × H (mm)",
          "3,500 × 2,150 × 2,900",
          "4,100 × 2,250 × 3,200",
          "4,550 × 2,300 × 3,900",
        ],
        ["Machine weight (kg)", "6,500", "9,500", "17,000"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=18",
      referenceNote,
    ),
    table(
      "Optional / additional features",
      cFrameCeramicModels,
      [
        ["Shuttle table (single / dual station)", "N/A", "Available", "Available"],
        ["Second ceramic tank", "Available", "Available", "Available"],
        ["Jib crane", "Available – 200 kg", "Available – 500 kg", "Available – 1,000 kg"],
        ["Platen heating system", "Available", "Available", "Available"],
        ["Electrical self-diagnostic", "Available", "Available", "Available"],
      ],
      "https://www.modtechworld.com/product-detail.php?id=18",
    ),
  ],
};
