INSERT INTO public.blog_posts (slug, title, excerpt, body, cover_url, category, kind, tags, author, read_minutes, pinned, published, published_at) VALUES
('robotic-case-erector-end-of-line', 'Robotic Case Erector: automating the start of your packaging line',
 'How a 6-axis robot handling multiple case magazines, a bottom flap folder and a sealing head removes the slowest manual step in end-of-line packaging.',
 E'Modtech Automation provides an automated end-of-line packaging solution for the erection of corrugated boxes and bottom sealing. The robotic case erector combines a 6-axis robot handling multiple case magazines with a bottom flap folder and a case sealing head — a fast and efficient way of completely automating your packaging line.\n\n## Value addition\n\n- Eliminates error and gives much more repeatability and reliability.\n- Maintains repeatable operation throughout the batch, with no or minimum changeover between SKUs.\n- Small footprint, high uptime and very low maintenance.\n- Rugged design suited to any production environment.\n- Easy to integrate with an existing line.\n- Recipe function for running different SKUs on the same or a different line.\n- Industry 4.0 enabled.\n\nThe cell is capable of handling multiple SKUs on the same line. Depending on the achievable cycle time, one system can cater to more than one line of cartons, cases and products.\n\n## The system includes\n\n- Robotic box erector system\n- Top and bottom taping machine\n- Box handling conveyors\n- An infeed conveyor integrated with the output of your production process\n- Touch-screen control system with surplus capacity for remote production logging and monitoring\n- Recipe function for running different SKUs on the same line\n- Guarding and doors with interlocks and safety as required\n- Custom-built robot gripper (vacuum-based or mechanical, depending on the product)\n- Ethernet connectivity for remote support\n\nThis is a fully integrated robotic automation system: design, build, installation, integration with your machinery, commissioning and basic operator training. The configuration can be modified to suit almost any requirement — layout, guarding, box types, label types and inkjet peripherals.',
 '/__l5e/assets-v1/cc7f7480-4829-4caa-b8c6-3b413835fe7e/case-erector.png', 'automation', 'article',
 ARRAY['case erector','end of line','packaging','robotics'], 'Modtech Automation', 4, true, true, now() - interval '40 days'),

('robotic-case-packer-multi-sku', 'Robotic Case Packer: filling, sealing and coding without operators',
 'A complete box filling line where a servo-controlled 6-axis robot packs the case, with sealing, labelling and inkjet coding as peripherals.',
 E'Modtech Automation delivers a complete box filling and packaging line in which the products are placed into the box by a robot. Sealing, labelling and inkjet printing of the boxes are added as peripherals to the system. The robotic case packer is a fast and efficient way of completely automating your packaging lines.\n\n## Value addition\n\n- Eliminates error and adds reliability across the line.\n- Maintains repeatable operation throughout the batch.\n- Very low maintenance.\n- Automatic tool changers.\n- Tooling adjustable for a wide range of product sizes with pick and place positions.\n- Operator pendant for recipe management, error reporting and diagnostics.\n- Capable of handling multiple product sizes.\n- Precise 6-axis robot with a servo-controlled system.\n- Remote support module for worldwide support.\n- Industry 4.0 enabled.\n\n## The system includes\n\n- Robotic box filling system\n- Top and bottom taping machine\n- Box handling conveyors\n- An infeed conveyor integrated with the output of your production process\n- Touch-screen control system with recipe management\n- Guarding and interlocked safety doors\n- Ethernet connectivity for remote support\n\nThis is a fully integrated robotic automation project including design, build, installation, integration with your machinery, commissioning and basic training in the use of the system.',
 '/__l5e/assets-v1/4b07a8e1-75f4-4a1c-8998-7c30ec2476ac/case-packer.png', 'automation', 'article',
 ARRAY['case packer','packaging','fmcg','robotics'], 'Modtech Automation', 4, false, true, now() - interval '34 days'),

('robotic-palletizing-systems', 'Robotic Palletizing: a fully automatic pallet line, from feeder to finished stack',
 'Pallet feeding, stacking and stretch-ready output configured for your products and plant layout — running without operator input.',
 E'Robotic palletizing at Modtech includes a pallet feeder and can be configured for several different types of products and plant layouts. It is a fully automatic system that runs without any operator input apart from loading a stack of pallets and taking finished pallets off the process.\n\n## Value addition\n\n- Reduces severe injury and fatigue to workers.\n- Increases production throughput, productivity and efficiency.\n- Very low maintenance.\n- Eliminates errors, giving much more repeatability and reliability.\n- Industry 4.0 enabled.\n\nThe system is capable of handling multiple SKUs at the same time. According to the client requirement and the achievable cycle time, one system can cater to more than one line of cartons, cases and products.\n\n## The system includes\n\n- Robotic palletizer\n- Automatic pallet feeding system\n- Pallet feeding conveyors\n- An infeed conveyor integrated with the output of your production process\n- Touch-screen control system with capacity for remote production logging and monitoring\n- Guarding doors with interlocks and safety as required\n- Custom-built robot gripper (vacuum-based or mechanical)\n- Ethernet connectivity for remote support',
 '/__l5e/assets-v1/e5aafa80-53b6-48dc-973c-df7f36a2790b/palletizer.png', 'automation', 'article',
 ARRAY['palletizing','material handling','end of line'], 'Modtech Automation', 3, false, true, now() - interval '28 days'),

('robotic-pick-and-place-vision', 'Robotic Pick & Place: high-speed handling with vision-guided sorting',
 'Bin picking, sorting, defect removal, assembly and packaging — configured for multiple product types and plant layouts.',
 E'The robotic handling or pick and place system can be configured for multiple different types of products and plant layouts. It allows a robotic handling cell to run without any operator input while picking and placing parts from one process into another — reducing repetitive strain injury and worker fatigue while increasing production throughput, productivity and efficiency.\n\n## Value addition\n\n- High picking accuracy and repeatable work.\n- Extremely high-speed output.\n- The robot instantly picks and separates different types of products passing through its area; with a vision camera it sorts products, packs them into designated containers and separates defective items.\n- Mainly used for higher speed applications such as bin picking, sorting, defect removal, assembly, packaging and inspection.\n- Industry 4.0 enabled.\n\n## The system includes\n\n- Robot for pick and place\n- Touch-screen control system with remote production logging and monitoring capacity\n- Vision camera for checking fill level, orientation and scanning\n- Guarding and doors with interlocks and safety as required\n- Bespoke robot gripper suited to the complexity of your product\n- A basic conveyor and, where required, a product station\n\nThe configuration can be modified to suit almost any requirement — layout, guarding, how many products the robot picks at once, stacking configuration and much more.',
 '/__l5e/assets-v1/1f95ae9e-e5c1-4941-8d9a-e358df132745/robot-6-axis.jpg', 'robotics', 'article',
 ARRAY['pick and place','vision','bin picking','robotics'], 'Modtech Automation', 4, false, true, now() - interval '22 days'),

('machine-tending-cnc-injection-wax', 'Machine Tending: CNC, plastic injection, wax injection and press cells',
 'Robots loading and unloading machines around the clock — consistent cycle times, higher uptime and safer operators.',
 E'Modtech provides loading and unloading of components from CNC machines using industrial robots, increasing productivity, consistency and operational efficiency. Robots accurately handle raw material and finished parts, ensuring consistent cycle times and repeatable quality across every operation.\n\n## Applications we deploy\n\n- **Plastic injection — part take out.** The robot removes moulded parts from the press and places them for downstream processing.\n- **CNC machine tending.** Raw blanks in, finished parts out, across single machines or multi-machine cells.\n- **Wax injection — complete cell.** A full cell including pre and post processing, such as robotic flash removal stations.\n- **Laminates and copper clad laminate.** Assembly and press tending for sheet handling.\n\n## Key benefits\n\n- Increased productivity and machine uptime\n- Consistent and repeatable part handling\n- Reduced labour costs and operator fatigue\n- Improved workplace safety\n- Scalable and flexible automation solutions',
 '/__l5e/assets-v1/71691c09-009d-4143-832b-51f114ccda8a/machine-tending.png', 'robotics', 'article',
 ARRAY['machine tending','cnc','wax injection','plastics'], 'Modtech Automation', 3, false, true, now() - interval '15 days'),

('robot-vision-systems-explained', 'Vision Systems: giving the robot eyes on the production line',
 'Cameras, lighting, software and conveyor tracking that let a robot find, inspect and pick parts while they are still moving.',
 E'A robotic vision system consists of one or more cameras, special purpose lighting, software and a robot. The camera takes a picture of the working area or the object the robot will grip, and the software searches the image for features that let it determine position and orientation. This information is sent to the robot controller and the programmed positions are updated. Depending on the application, the camera may be mounted on the robot or fixed within the cell. Calibration relates the vision coordinate space to the robot.\n\n## What vision can do\n\n- Checking orientation\n- Fill level checking\n- Checking barcode printing\n- Detecting dents and scratches on the product\n- Label print verification via OCR and OCV\n- Detection of parts\n- Calculating the volume of items passing along a conveyor\n- Monitoring product quality within a production process\n- Aligning parts accurately for assembly\n- Pick and place applications\n\n## Conveyor tracking\n\nConveyor tracking is often useful in packaging applications. The product moves into the robot cell on a conveyor without stopping. The vision system determines accurate part position and the robot controller adds speed information from the belt encoder, letting the robot track and pick while the product is in motion. Rather than presenting every piece in precisely the same location and orientation, a vision system simplifies cell design and lowers cost — making robotic automation far easier to justify.',
 '/__l5e/assets-v1/13562143-9915-4ac0-8740-1aa41ff673a4/robot-cobot.png', 'automation', 'blog',
 ARRAY['vision','inspection','industry 4.0'], 'Modtech Automation', 4, false, true, now() - interval '7 days')
ON CONFLICT (slug) DO NOTHING;